export const INITIALIZED = "INITIALIZED"
export const CATEGORIES = "CATEGORIES"
export const CART = "CART"
export const ITEMS = "ITEMS"
export const SURPRISES = "SURPRISES"
export const USER = "USER"
export const LOGOUT = "LOGOUT"
export const FETCH_USER_TIME = "FETCH_USER_TIME"
export const BRETHREN = "BRETHREN"
export const JOBS = "JOBS"
export const EVENTS = "EVENTS"
export const FELLOWSHIPTOPAY = "FELLOWSHIPTOPAY"
export const STATE = "STATE"
export const CONNECT_USER = "CONNECT_USER" //  user to connect withh
export const LOCATION = "LOCATION" // user current location
export const NOTIFICATION = 'NOTIFICATION' // Notification
export const SCANEUSER = 'SCANEUSER' // SCANNED USER
export const AUTHENTICATIONFELLOWSHIP = 'AUTHENTICATIONFELLOWSHIP' // SCANNED USER
export const MEETINGS = 'MEETINGS' // SCANNED USER
export const BETHELS = 'BETHELS' // BETHELS
export const DELTAS = 'DELTAS' // DELTAS
export const ENROUTE = 'ENROUTE' // ENROUTE
